services:
  api:
    container_name: shortener_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - shortener_network
    restart: always
  mongodb:
    container_name: shortener_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - shortener_network
    volumes:
      - mongodb_data:/data/db
networks:
  shortener_network:
    driver: bridge

volumes:
  mongodb_data: