services:
  api:
    container_name: shortener_api
    build: ./back-end/
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    networks:
      - shortener_network
    restart: always

  frontend:
    container_name: shortener_frontend
    build: ./front-end/
    env_file:
      - ./front-end/.env
    volumes:
      - frontend_volume:/var/www/html

  nginx:
    container_name: shortener_nginx
    build: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - frontend_volume:/var/www/html
    depends_on:
      - mongodb
      - api
      - frontend
  mongodb:
    container_name: shortener_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - shortener_network
    volumes:
      - mongodb_data:/data/db
networks:
  shortener_network:
    driver: bridge

volumes:
  mongodb_data:
  frontend_volume: